# Generated by Django 5.0.14 on 2026-07-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='PersonalSeguridad',
            fields=[
            ],
            options={
                'verbose_name': 'Personal Seguridad',
                'verbose_name_plural': 'Personal Seguridad',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuario',),
        ),
    ]
