# Generated by Django 5.0.14 on 2026-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('numero_identidad', models.CharField(max_length=20, unique=True, verbose_name='Cédula o ID')),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Administrativo', 'Administrativo'), ('Visitante', 'Visitante')], default='Estudiante', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietario',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
