# Generated by Django 5.0.14 on 2026-07-13 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id_codigo_qr', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_qr', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'db_table': 'codigo_qr',
            },
        ),
    ]
