# Generated by Django 6.0.7 on 2026-07-13 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_historialingreso'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMovimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], default='INGRESO', max_length=10)),
                ('estado', models.CharField(choices=[('AUTORIZADO', 'Autorizado'), ('DENEGADO', 'Denegado')], default='DENEGADO', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='qr.codigoqr')),
                ('usuario_validador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Movimiento',
                'verbose_name_plural': 'Registros de Movimiento',
                'db_table': 'registro_movimiento',
                'ordering': ['-fecha'],
            },
        ),
    ]
