# Generated by Django 5.0.14 on 2026-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_registromovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración QR', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('expiration_days', models.PositiveIntegerField(default=30)),
                ('activar_qr', models.BooleanField(default=True)),
                ('permitir_reutilizacion', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración QR',
                'verbose_name_plural': 'Configuraciones QR',
            },
        ),
    ]
