# Generated by Django 5.0.14 on 2026-07-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('AUTORIZADO', 'Autorizado para ingresar'), ('NO_AUTORIZADO', 'No autorizado'), ('SUSPENDIDO', 'Acceso suspendido')], default='AUTORIZADO', max_length=50)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='propietarios.propietario', verbose_name='Propietario del Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
